### ISSUE TITLE
Same issues with HP Omen 17 (2019)

### ISSUE THREAD

**Issue by bensuperpc** [dhedlund/kernel-patch-lg-gram-17#2]
I have same issue with my HP Omen 17 (2019),
I add GRUB option "pci=nommconf", it working with well performance in games and vidéo maker but I have not tested more.

**Comment by barius** [comment]
I have tested this patch on my HP Omen 17 on Ubuntu 19.04 with kernel 5.0.0-27-generic. It works fine.
Before this I tested pci=nommconf and acpi=off, both renders some issues (either black screen or GPU not working or scrambled display, etc.).
For me, this patch seems to be the only cure.

So any updates on the ubuntu kernel source? Did they fix this issue?

**Comment by bensuperpc** [comment]
Fixed with Linux 5.9
